/**
 * ```
 * aws ec2 describe-instance-types | \
 * jq '.InstanceTypes | map(select( (.SupportedVirtualizationTypes[] | contains("hvm")) and (.InstanceType | test("^(m7|t3|c7|r7|p5|g5)")) )) | map( { "name": .InstanceType, "arch": ( .ProcessorInfo.SupportedArchitectures | join(",") ), "cpus": .VCpuInfo.DefaultVCpus, "memory": (.MemoryInfo.SizeInMiB / 1024), "gpus": ( if (.GpuInfo == null) then 0 else .GpuInfo.Gpus[0].Count end) } )'
 * ```
 */
export const INSTANCE_TYPES: {
  name: string;
  arch: string;
  cpus: number;
  memory: number;
  gpus: number;
}[] = [
  {
    name: "m7g.4xlarge",
    arch: "arm64",
    cpus: 16,
    memory: 64,
    gpus: 0,
  },
  {
    name: "m7i.16xlarge",
    arch: "x86_64",
    cpus: 64,
    memory: 256,
    gpus: 0,
  },
  {
    name: "c7gd.medium",
    arch: "arm64",
    cpus: 1,
    memory: 2,
    gpus: 0,
  },
  {
    name: "c7i.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 16,
    gpus: 0,
  },
  {
    name: "r7a.32xlarge",
    arch: "x86_64",
    cpus: 128,
    memory: 1024,
    gpus: 0,
  },
  {
    name: "c7gn.16xlarge",
    arch: "arm64",
    cpus: 64,
    memory: 128,
    gpus: 0,
  },
  {
    name: "g5.4xlarge",
    arch: "x86_64",
    cpus: 16,
    memory: 64,
    gpus: 1,
  },
  {
    name: "m7gd.16xlarge",
    arch: "arm64",
    cpus: 64,
    memory: 256,
    gpus: 0,
  },
  {
    name: "c7g.8xlarge",
    arch: "arm64",
    cpus: 32,
    memory: 64,
    gpus: 0,
  },
  {
    name: "r7a.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 64,
    gpus: 0,
  },
  {
    name: "m7gd.large",
    arch: "arm64",
    cpus: 2,
    memory: 8,
    gpus: 0,
  },
  {
    name: "m7gd.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 16,
    gpus: 0,
  },
  {
    name: "g5.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 32,
    gpus: 1,
  },
  {
    name: "r7a.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 32,
    gpus: 0,
  },
  {
    name: "c7gn.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 8,
    gpus: 0,
  },
  {
    name: "r7gd.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 32,
    gpus: 0,
  },
  {
    name: "c7gn.8xlarge",
    arch: "arm64",
    cpus: 32,
    memory: 64,
    gpus: 0,
  },
  {
    name: "r7a.4xlarge",
    arch: "x86_64",
    cpus: 16,
    memory: 128,
    gpus: 0,
  },
  {
    name: "c7g.4xlarge",
    arch: "arm64",
    cpus: 16,
    memory: 32,
    gpus: 0,
  },
  {
    name: "m7a.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 16,
    gpus: 0,
  },
  {
    name: "r7gd.8xlarge",
    arch: "arm64",
    cpus: 32,
    memory: 192,
    gpus: 0,
  },
  {
    name: "r7gd.16xlarge",
    arch: "arm64",
    cpus: 64,
    memory: 512,
    gpus: 0,
  },
  {
    name: "m7i.24xlarge",
    arch: "x86_64",
    cpus: 96,
    memory: 384,
    gpus: 0,
  },
  {
    name: "c7i.8xlarge",
    arch: "x86_64",
    cpus: 32,
    memory: 64,
    gpus: 0,
  },
  {
    name: "r7g.medium",
    arch: "arm64",
    cpus: 1,
    memory: 8,
    gpus: 0,
  },
  {
    name: "t3.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 32,
    gpus: 0,
  },
  {
    name: "m7g.large",
    arch: "arm64",
    cpus: 2,
    memory: 8,
    gpus: 0,
  },
  {
    name: "m7i.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 32,
    gpus: 0,
  },
  {
    name: "c7g.16xlarge",
    arch: "arm64",
    cpus: 64,
    memory: 128,
    gpus: 0,
  },
  {
    name: "c7gn.large",
    arch: "arm64",
    cpus: 2,
    memory: 4,
    gpus: 0,
  },
  {
    name: "t3a.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 32,
    gpus: 0,
  },
  {
    name: "m7i-flex.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 32,
    gpus: 0,
  },
  {
    name: "m7g.12xlarge",
    arch: "arm64",
    cpus: 48,
    memory: 192,
    gpus: 0,
  },
  {
    name: "m7i.8xlarge",
    arch: "x86_64",
    cpus: 32,
    memory: 128,
    gpus: 0,
  },
  {
    name: "m7a.16xlarge",
    arch: "x86_64",
    cpus: 64,
    memory: 256,
    gpus: 0,
  },
  {
    name: "r7a.large",
    arch: "x86_64",
    cpus: 2,
    memory: 16,
    gpus: 0,
  },
  {
    name: "t3.medium",
    arch: "x86_64",
    cpus: 2,
    memory: 4,
    gpus: 0,
  },
  {
    name: "t3.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 16,
    gpus: 0,
  },
  {
    name: "m7g.16xlarge",
    arch: "arm64",
    cpus: 64,
    memory: 256,
    gpus: 0,
  },
  {
    name: "r7g.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 64,
    gpus: 0,
  },
  {
    name: "c7i.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 8,
    gpus: 0,
  },
  {
    name: "r7a.medium",
    arch: "x86_64",
    cpus: 1,
    memory: 8,
    gpus: 0,
  },
  {
    name: "c7i.large",
    arch: "x86_64",
    cpus: 2,
    memory: 4,
    gpus: 0,
  },
  {
    name: "c7g.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 8,
    gpus: 0,
  },
  {
    name: "t3a.small",
    arch: "x86_64",
    cpus: 2,
    memory: 2,
    gpus: 0,
  },
  {
    name: "m7gd.12xlarge",
    arch: "arm64",
    cpus: 48,
    memory: 192,
    gpus: 0,
  },
  {
    name: "c7gd.large",
    arch: "arm64",
    cpus: 2,
    memory: 4,
    gpus: 0,
  },
  {
    name: "t3.large",
    arch: "x86_64",
    cpus: 2,
    memory: 8,
    gpus: 0,
  },
  {
    name: "t3a.medium",
    arch: "x86_64",
    cpus: 2,
    memory: 4,
    gpus: 0,
  },
  {
    name: "c7i.16xlarge",
    arch: "x86_64",
    cpus: 64,
    memory: 128,
    gpus: 0,
  },
  {
    name: "m7gd.8xlarge",
    arch: "arm64",
    cpus: 32,
    memory: 128,
    gpus: 0,
  },
  {
    name: "m7a.32xlarge",
    arch: "x86_64",
    cpus: 128,
    memory: 512,
    gpus: 0,
  },
  {
    name: "r7g.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 32,
    gpus: 0,
  },
  {
    name: "g5.24xlarge",
    arch: "x86_64",
    cpus: 96,
    memory: 384,
    gpus: 4,
  },
  {
    name: "c7gd.16xlarge",
    arch: "arm64",
    cpus: 64,
    memory: 128,
    gpus: 0,
  },
  {
    name: "m7g.8xlarge",
    arch: "arm64",
    cpus: 32,
    memory: 128,
    gpus: 0,
  },
  {
    name: "r7g.metal",
    arch: "arm64",
    cpus: 64,
    memory: 512,
    gpus: 0,
  },
  {
    name: "m7a.medium",
    arch: "x86_64",
    cpus: 1,
    memory: 4,
    gpus: 0,
  },
  {
    name: "r7a.24xlarge",
    arch: "x86_64",
    cpus: 96,
    memory: 768,
    gpus: 0,
  },
  {
    name: "t3.nano",
    arch: "x86_64",
    cpus: 2,
    memory: 0.5,
    gpus: 0,
  },
  {
    name: "m7gd.medium",
    arch: "arm64",
    cpus: 1,
    memory: 4,
    gpus: 0,
  },
  {
    name: "m7g.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 16,
    gpus: 0,
  },
  {
    name: "c7i.24xlarge",
    arch: "x86_64",
    cpus: 96,
    memory: 192,
    gpus: 0,
  },
  {
    name: "m7i.48xlarge",
    arch: "x86_64",
    cpus: 192,
    memory: 768,
    gpus: 0,
  },
  {
    name: "m7gd.4xlarge",
    arch: "arm64",
    cpus: 16,
    memory: 64,
    gpus: 0,
  },
  {
    name: "r7gd.medium",
    arch: "arm64",
    cpus: 1,
    memory: 8,
    gpus: 0,
  },
  {
    name: "r7gd.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 64,
    gpus: 0,
  },
  {
    name: "r7gd.4xlarge",
    arch: "arm64",
    cpus: 16,
    memory: 128,
    gpus: 0,
  },
  {
    name: "g5.12xlarge",
    arch: "x86_64",
    cpus: 48,
    memory: 192,
    gpus: 4,
  },
  {
    name: "c7gd.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 8,
    gpus: 0,
  },
  {
    name: "m7a.48xlarge",
    arch: "x86_64",
    cpus: 192,
    memory: 768,
    gpus: 0,
  },
  {
    name: "r7g.8xlarge",
    arch: "arm64",
    cpus: 32,
    memory: 256,
    gpus: 0,
  },
  {
    name: "c7g.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 16,
    gpus: 0,
  },
  {
    name: "m7a.24xlarge",
    arch: "x86_64",
    cpus: 96,
    memory: 384,
    gpus: 0,
  },
  {
    name: "c7gd.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 16,
    gpus: 0,
  },
  {
    name: "r7a.8xlarge",
    arch: "x86_64",
    cpus: 32,
    memory: 256,
    gpus: 0,
  },
  {
    name: "c7gd.8xlarge",
    arch: "arm64",
    cpus: 32,
    memory: 64,
    gpus: 0,
  },
  {
    name: "g5.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 16,
    gpus: 1,
  },
  {
    name: "m7i-flex.4xlarge",
    arch: "x86_64",
    cpus: 16,
    memory: 64,
    gpus: 0,
  },
  {
    name: "g5.16xlarge",
    arch: "x86_64",
    cpus: 64,
    memory: 256,
    gpus: 1,
  },
  {
    name: "m7a.8xlarge",
    arch: "x86_64",
    cpus: 32,
    memory: 128,
    gpus: 0,
  },
  {
    name: "t3a.large",
    arch: "x86_64",
    cpus: 2,
    memory: 8,
    gpus: 0,
  },
  {
    name: "c7g.medium",
    arch: "arm64",
    cpus: 1,
    memory: 2,
    gpus: 0,
  },
  {
    name: "m7a.4xlarge",
    arch: "x86_64",
    cpus: 16,
    memory: 64,
    gpus: 0,
  },
  {
    name: "t3.micro",
    arch: "x86_64",
    cpus: 2,
    memory: 1,
    gpus: 0,
  },
  {
    name: "r7g.4xlarge",
    arch: "arm64",
    cpus: 16,
    memory: 128,
    gpus: 0,
  },
  {
    name: "m7g.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 32,
    gpus: 0,
  },
  {
    name: "r7gd.large",
    arch: "arm64",
    cpus: 2,
    memory: 16,
    gpus: 0,
  },
  {
    name: "m7i.large",
    arch: "x86_64",
    cpus: 2,
    memory: 8,
    gpus: 0,
  },
  {
    name: "c7g.metal",
    arch: "arm64",
    cpus: 64,
    memory: 128,
    gpus: 0,
  },
  {
    name: "m7a.12xlarge",
    arch: "x86_64",
    cpus: 48,
    memory: 192,
    gpus: 0,
  },
  {
    name: "m7a.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 32,
    gpus: 0,
  },
  {
    name: "c7g.12xlarge",
    arch: "arm64",
    cpus: 48,
    memory: 96,
    gpus: 0,
  },
  {
    name: "c7i.4xlarge",
    arch: "x86_64",
    cpus: 16,
    memory: 32,
    gpus: 0,
  },
  {
    name: "c7gd.12xlarge",
    arch: "arm64",
    cpus: 48,
    memory: 96,
    gpus: 0,
  },
  {
    name: "m7i.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 16,
    gpus: 0,
  },
  {
    name: "r7gd.12xlarge",
    arch: "arm64",
    cpus: 48,
    memory: 256,
    gpus: 0,
  },
  {
    name: "c7g.large",
    arch: "arm64",
    cpus: 2,
    memory: 4,
    gpus: 0,
  },
  {
    name: "m7g.medium",
    arch: "arm64",
    cpus: 1,
    memory: 4,
    gpus: 0,
  },
  {
    name: "c7i.12xlarge",
    arch: "x86_64",
    cpus: 48,
    memory: 96,
    gpus: 0,
  },
  {
    name: "m7g.metal",
    arch: "arm64",
    cpus: 64,
    memory: 256,
    gpus: 0,
  },
  {
    name: "m7i-flex.8xlarge",
    arch: "x86_64",
    cpus: 32,
    memory: 128,
    gpus: 0,
  },
  {
    name: "r7a.12xlarge",
    arch: "x86_64",
    cpus: 48,
    memory: 384,
    gpus: 0,
  },
  {
    name: "r7g.large",
    arch: "arm64",
    cpus: 2,
    memory: 16,
    gpus: 0,
  },
  {
    name: "t3.small",
    arch: "x86_64",
    cpus: 2,
    memory: 2,
    gpus: 0,
  },
  {
    name: "c7gn.12xlarge",
    arch: "arm64",
    cpus: 48,
    memory: 96,
    gpus: 0,
  },
  {
    name: "m7gd.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 32,
    gpus: 0,
  },
  {
    name: "m7i.4xlarge",
    arch: "x86_64",
    cpus: 16,
    memory: 64,
    gpus: 0,
  },
  {
    name: "c7i.48xlarge",
    arch: "x86_64",
    cpus: 192,
    memory: 384,
    gpus: 0,
  },
  {
    name: "c7gn.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 16,
    gpus: 0,
  },
  {
    name: "g5.48xlarge",
    arch: "x86_64",
    cpus: 192,
    memory: 768,
    gpus: 8,
  },
  {
    name: "m7i.12xlarge",
    arch: "x86_64",
    cpus: 48,
    memory: 192,
    gpus: 0,
  },
  {
    name: "t3a.micro",
    arch: "x86_64",
    cpus: 2,
    memory: 1,
    gpus: 0,
  },
  {
    name: "t3a.nano",
    arch: "x86_64",
    cpus: 2,
    memory: 0.5,
    gpus: 0,
  },
  {
    name: "r7a.48xlarge",
    arch: "x86_64",
    cpus: 192,
    memory: 1536,
    gpus: 0,
  },
  {
    name: "m7i-flex.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 16,
    gpus: 0,
  },
  {
    name: "c7gn.4xlarge",
    arch: "arm64",
    cpus: 16,
    memory: 32,
    gpus: 0,
  },
  {
    name: "m7a.metal-48xl",
    arch: "x86_64",
    cpus: 192,
    memory: 768,
    gpus: 0,
  },
  {
    name: "r7g.16xlarge",
    arch: "arm64",
    cpus: 64,
    memory: 512,
    gpus: 0,
  },
  {
    name: "c7gn.medium",
    arch: "arm64",
    cpus: 1,
    memory: 2,
    gpus: 0,
  },
  {
    name: "r7g.12xlarge",
    arch: "arm64",
    cpus: 48,
    memory: 384,
    gpus: 0,
  },
  {
    name: "r7a.16xlarge",
    arch: "x86_64",
    cpus: 64,
    memory: 512,
    gpus: 0,
  },
  {
    name: "m7a.large",
    arch: "x86_64",
    cpus: 2,
    memory: 8,
    gpus: 0,
  },
  {
    name: "g5.8xlarge",
    arch: "x86_64",
    cpus: 32,
    memory: 128,
    gpus: 1,
  },
  {
    name: "c7gd.4xlarge",
    arch: "arm64",
    cpus: 16,
    memory: 32,
    gpus: 0,
  },
  {
    name: "m7i-flex.large",
    arch: "x86_64",
    cpus: 2,
    memory: 8,
    gpus: 0,
  },
  {
    name: "t3a.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 16,
    gpus: 0,
  },
];
