import { InstanceType } from "../instance-type";

/**
 * Selecting from:
 * - Non-production: t3 and t4g
 * - General Purpose (CPU/memory = 1/4): m6i and m7g
 * - CPU Optimized (CPU/memory = 1/2): c6i and c7g
 * - Memory Optimized (CPU/memory = 1/8): r6i and r7g
 * - GPU: g5 ang g5g
 *
 * Why Intel v7 and ARM v6? Because Amazon is not consistent with availability or sizing.
 * At the time of writing the intal v7 instances were basically not available anywhere.
 */

export const INSTANCE_TYPES: InstanceType[] = [
  {
    name: "c6i.12xlarge",
    arch: "x86_64",
    cpus: 48,
    memory: 96,
    gpus: 0,
    prod: true,
  },
  {
    name: "c6i.16xlarge",
    arch: "x86_64",
    cpus: 64,
    memory: 128,
    gpus: 0,
    prod: true,
  },
  {
    name: "c6i.24xlarge",
    arch: "x86_64",
    cpus: 96,
    memory: 192,
    gpus: 0,
    prod: true,
  },
  {
    name: "c6i.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 16,
    gpus: 0,
    prod: true,
  },
  {
    name: "c6i.32xlarge",
    arch: "x86_64",
    cpus: 128,
    memory: 256,
    gpus: 0,
    prod: true,
  },
  {
    name: "c6i.4xlarge",
    arch: "x86_64",
    cpus: 16,
    memory: 32,
    gpus: 0,
    prod: true,
  },
  {
    name: "c6i.8xlarge",
    arch: "x86_64",
    cpus: 32,
    memory: 64,
    gpus: 0,
    prod: true,
  },
  {
    name: "c6i.large",
    arch: "x86_64",
    cpus: 2,
    memory: 4,
    gpus: 0,
    prod: true,
  },
  {
    name: "c6i.metal",
    arch: "x86_64",
    cpus: 128,
    memory: 256,
    gpus: 0,
    prod: true,
  },
  {
    name: "c6i.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 8,
    gpus: 0,
    prod: true,
  },
  {
    name: "c7g.12xlarge",
    arch: "arm64",
    cpus: 48,
    memory: 96,
    gpus: 0,
    prod: true,
  },
  {
    name: "c7g.16xlarge",
    arch: "arm64",
    cpus: 64,
    memory: 128,
    gpus: 0,
    prod: true,
  },
  {
    name: "c7g.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 16,
    gpus: 0,
    prod: true,
  },
  {
    name: "c7g.4xlarge",
    arch: "arm64",
    cpus: 16,
    memory: 32,
    gpus: 0,
    prod: true,
  },
  {
    name: "c7g.8xlarge",
    arch: "arm64",
    cpus: 32,
    memory: 64,
    gpus: 0,
    prod: true,
  },
  {
    name: "c7g.large",
    arch: "arm64",
    cpus: 2,
    memory: 4,
    gpus: 0,
    prod: true,
  },
  {
    name: "c7g.medium",
    arch: "arm64",
    cpus: 1,
    memory: 2,
    gpus: 0,
    prod: true,
  },
  {
    name: "c7g.metal",
    arch: "arm64",
    cpus: 64,
    memory: 128,
    gpus: 0,
    prod: true,
  },
  {
    name: "c7g.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 8,
    gpus: 0,
    prod: true,
  },
  {
    name: "g5.12xlarge",
    arch: "x86_64",
    cpus: 48,
    memory: 192,
    gpus: 4,
    prod: true,
  },
  {
    name: "g5.16xlarge",
    arch: "x86_64",
    cpus: 64,
    memory: 256,
    gpus: 1,
    prod: true,
  },
  {
    name: "g5.24xlarge",
    arch: "x86_64",
    cpus: 96,
    memory: 384,
    gpus: 4,
    prod: true,
  },
  {
    name: "g5.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 32,
    gpus: 1,
    prod: true,
  },
  {
    name: "g5.48xlarge",
    arch: "x86_64",
    cpus: 192,
    memory: 768,
    gpus: 8,
    prod: true,
  },
  {
    name: "g5.4xlarge",
    arch: "x86_64",
    cpus: 16,
    memory: 64,
    gpus: 1,
    prod: true,
  },
  {
    name: "g5.8xlarge",
    arch: "x86_64",
    cpus: 32,
    memory: 128,
    gpus: 1,
    prod: true,
  },
  {
    name: "g5.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 16,
    gpus: 1,
    prod: true,
  },
  {
    name: "m6i.12xlarge",
    arch: "x86_64",
    cpus: 48,
    memory: 192,
    gpus: 0,
    prod: true,
  },
  {
    name: "m6i.16xlarge",
    arch: "x86_64",
    cpus: 64,
    memory: 256,
    gpus: 0,
    prod: true,
  },
  {
    name: "m6i.24xlarge",
    arch: "x86_64",
    cpus: 96,
    memory: 384,
    gpus: 0,
    prod: true,
  },
  {
    name: "m6i.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 32,
    gpus: 0,
    prod: true,
  },
  {
    name: "m6i.32xlarge",
    arch: "x86_64",
    cpus: 128,
    memory: 512,
    gpus: 0,
    prod: true,
  },
  {
    name: "m6i.4xlarge",
    arch: "x86_64",
    cpus: 16,
    memory: 64,
    gpus: 0,
    prod: true,
  },
  {
    name: "m6i.8xlarge",
    arch: "x86_64",
    cpus: 32,
    memory: 128,
    gpus: 0,
    prod: true,
  },
  {
    name: "m6i.large",
    arch: "x86_64",
    cpus: 2,
    memory: 8,
    gpus: 0,
    prod: true,
  },
  {
    name: "m6i.metal",
    arch: "x86_64",
    cpus: 128,
    memory: 512,
    gpus: 0,
    prod: true,
  },
  {
    name: "m6i.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 16,
    gpus: 0,
    prod: true,
  },
  {
    name: "m7g.12xlarge",
    arch: "arm64",
    cpus: 48,
    memory: 192,
    gpus: 0,
    prod: true,
  },
  {
    name: "m7g.16xlarge",
    arch: "arm64",
    cpus: 64,
    memory: 256,
    gpus: 0,
    prod: true,
  },
  {
    name: "m7g.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 32,
    gpus: 0,
    prod: true,
  },
  {
    name: "m7g.4xlarge",
    arch: "arm64",
    cpus: 16,
    memory: 64,
    gpus: 0,
    prod: true,
  },
  {
    name: "m7g.8xlarge",
    arch: "arm64",
    cpus: 32,
    memory: 128,
    gpus: 0,
    prod: true,
  },
  {
    name: "m7g.large",
    arch: "arm64",
    cpus: 2,
    memory: 8,
    gpus: 0,
    prod: true,
  },
  {
    name: "m7g.medium",
    arch: "arm64",
    cpus: 1,
    memory: 4,
    gpus: 0,
    prod: true,
  },
  {
    name: "m7g.metal",
    arch: "arm64",
    cpus: 64,
    memory: 256,
    gpus: 0,
    prod: true,
  },
  {
    name: "m7g.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 16,
    gpus: 0,
    prod: true,
  },
  {
    name: "r6i.12xlarge",
    arch: "x86_64",
    cpus: 48,
    memory: 384,
    gpus: 0,
    prod: true,
  },
  {
    name: "r6i.16xlarge",
    arch: "x86_64",
    cpus: 64,
    memory: 512,
    gpus: 0,
    prod: true,
  },
  {
    name: "r6i.24xlarge",
    arch: "x86_64",
    cpus: 96,
    memory: 768,
    gpus: 0,
    prod: true,
  },
  {
    name: "r6i.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 64,
    gpus: 0,
    prod: true,
  },
  {
    name: "r6i.32xlarge",
    arch: "x86_64",
    cpus: 128,
    memory: 1024,
    gpus: 0,
    prod: true,
  },
  {
    name: "r6i.4xlarge",
    arch: "x86_64",
    cpus: 16,
    memory: 128,
    gpus: 0,
    prod: true,
  },
  {
    name: "r6i.8xlarge",
    arch: "x86_64",
    cpus: 32,
    memory: 256,
    gpus: 0,
    prod: true,
  },
  {
    name: "r6i.large",
    arch: "x86_64",
    cpus: 2,
    memory: 16,
    gpus: 0,
    prod: true,
  },
  {
    name: "r6i.metal",
    arch: "x86_64",
    cpus: 128,
    memory: 1024,
    gpus: 0,
    prod: true,
  },
  {
    name: "r6i.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 32,
    gpus: 0,
    prod: true,
  },
  {
    name: "r7g.12xlarge",
    arch: "arm64",
    cpus: 48,
    memory: 384,
    gpus: 0,
    prod: true,
  },
  {
    name: "r7g.16xlarge",
    arch: "arm64",
    cpus: 64,
    memory: 512,
    gpus: 0,
    prod: true,
  },
  {
    name: "r7g.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 64,
    gpus: 0,
    prod: true,
  },
  {
    name: "r7g.4xlarge",
    arch: "arm64",
    cpus: 16,
    memory: 128,
    gpus: 0,
    prod: true,
  },
  {
    name: "r7g.8xlarge",
    arch: "arm64",
    cpus: 32,
    memory: 256,
    gpus: 0,
    prod: true,
  },
  {
    name: "r7g.large",
    arch: "arm64",
    cpus: 2,
    memory: 16,
    gpus: 0,
    prod: true,
  },
  {
    name: "r7g.medium",
    arch: "arm64",
    cpus: 1,
    memory: 8,
    gpus: 0,
    prod: true,
  },
  {
    name: "r7g.metal",
    arch: "arm64",
    cpus: 64,
    memory: 512,
    gpus: 0,
    prod: true,
  },
  {
    name: "r7g.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 32,
    gpus: 0,
    prod: true,
  },
  {
    name: "t3.2xlarge",
    arch: "x86_64",
    cpus: 8,
    memory: 32,
    gpus: 0,
    prod: false,
  },
  {
    name: "t3.large",
    arch: "x86_64",
    cpus: 2,
    memory: 8,
    gpus: 0,
    prod: false,
  },
  {
    name: "t3.medium",
    arch: "x86_64",
    cpus: 2,
    memory: 4,
    gpus: 0,
    prod: false,
  },
  {
    name: "t3.micro",
    arch: "x86_64",
    cpus: 2,
    memory: 1,
    gpus: 0,
    prod: false,
  },
  {
    name: "t3.nano",
    arch: "x86_64",
    cpus: 2,
    memory: 0.5,
    gpus: 0,
    prod: false,
  },
  {
    name: "t3.small",
    arch: "x86_64",
    cpus: 2,
    memory: 2,
    gpus: 0,
    prod: false,
  },
  {
    name: "t3.xlarge",
    arch: "x86_64",
    cpus: 4,
    memory: 16,
    gpus: 0,
    prod: false,
  },
  {
    name: "t4g.2xlarge",
    arch: "arm64",
    cpus: 8,
    memory: 32,
    gpus: 0,
    prod: false,
  },
  {
    name: "t4g.large",
    arch: "arm64",
    cpus: 2,
    memory: 8,
    gpus: 0,
    prod: false,
  },
  {
    name: "t4g.medium",
    arch: "arm64",
    cpus: 2,
    memory: 4,
    gpus: 0,
    prod: false,
  },
  {
    name: "t4g.micro",
    arch: "arm64",
    cpus: 2,
    memory: 1,
    gpus: 0,
    prod: false,
  },
  {
    name: "t4g.nano",
    arch: "arm64",
    cpus: 2,
    memory: 0.5,
    gpus: 0,
    prod: false,
  },
  {
    name: "t4g.small",
    arch: "arm64",
    cpus: 2,
    memory: 2,
    gpus: 0,
    prod: false,
  },
  {
    name: "t4g.xlarge",
    arch: "arm64",
    cpus: 4,
    memory: 16,
    gpus: 0,
    prod: false,
  },
];
